export enum DelegationStatus {
  DelegationSuccessful,
  BinaryOpNoSupported,
  DataSourceNotDelegatable,
  UndelegatableFunction,
  AsyncPredicate,
  BinaryOpNotSupportedByTable,
  UnaryOpNotSupportedByTable,
  ImpureNode,
  NoDelSupportByColumn,
  UnSupportedSortArg,
  AsyncSortOrder,
  SortOrderNotSupportedByColumn,
  NotANumberArgType,
  InvalidArgType,
  UnSupportedRowScopedDottedNameNode,
  UnSupportedDistinctArg,
}
