// Operator strings which are part of delegation metadata Json.
// These are used when parsing the metadata Json.
export class DelegationMetadataOperatorConstants {
  public static Equal = 'eq'
  public static NotEqual = 'ne'
  public static Less = 'lt'
  public static LessEqual = 'le'
  public static Greater = 'gt'
  public static GreaterEqual = 'ge'
  public static And = 'and'
  public static Or = 'or'
  public static Contains = 'contains'
  public static IndexOf = 'indexof'
  public static SubStringOf = 'substringof'
  public static Not = 'not'
  public static Year = 'year'
  public static Month = 'month'
  public static Day = 'day'
  public static Hour = 'hour'
  public static Minute = 'minute'
  public static Second = 'second'
  public static Lower = 'tolower'
  public static Upper = 'toupper'
  public static Trim = 'trim'
  public static Null = 'null'
  public static Date = 'date'
  public static Length = 'length'
  public static Sum = 'sum'
  public static Min = 'min'
  public static Max = 'max'
  public static Average = 'average'
  public static Count = 'count'
  public static Add = 'add'
  public static Sub = 'sub'
  public static StartsWith = 'startswith'
  public static Mul = 'mul'
  public static Div = 'div'
  public static EndsWith = 'endswith'
  public static CountDistinct = 'countdistinct'
  public static CdsIn = 'cdsin'
  public static Top = 'top'
  public static AsType = 'astype'
  public static ArrayLookup = 'arraylookup'
}
